### ISSUE TITLE
As a client, I should be able to shop online for the items I want delivered.

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/food-bank-app#12]

**Comment by Yerniyaz** [comment]
Hello, let me take this issue? May you briefly describe needed functionalities in more details?

**Comment by DealPete** [comment]
Hi Yerniyaz,

This issue is something we were throwing around in brainstorming, but I don't see a pratical way to implement it. I'm definitely open for ideas, though, if you have them.

**Comment by adilbeknurmakov** [comment]
I could also check thaen it for bugs

**Comment by adilbeknurmakov** [comment]
When Yerniaz finishes implemantation
