### ISSUE TITLE
As an admin I should be able to add clients, volunteers, donors to the database without creating user accounts for each.

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/food-bank-app#16]
Currently the only way to add new users to the database (aside from running the "createAdminUser.js" script) is to log out of the app and go through the "sign up" process. The admin user should have a way to add new users to the database from the admin panel without logging out.

**Comment by nicholashu** [comment]
I might give this a go. Any tips?

**Comment by DealPete** [comment]
Right now you can edit a client from the "Client Database" tab by clicking on the edit button in his row. The edit screen allows you to change any details about the client. I think the easiest way to implement this would be to have an "add new client" button at the bottom of the table that automatically adds a new client to the database with some default settings, then takes the admin user to the edit page to fill in the details.

**Comment by nicholashu** [comment]
Should the newly created volunteers, clients and donors have user accounts or just database entries?

**Comment by DealPete** [comment]
Just database entries.

**Comment by DealPete** [comment]
Hi Nicholas,

I just realized that it's not going to work to just create database entries in customer, donor, and volunteer. Currently these get created dynamically from the corresponding user accounts, with the id set to the user's id. Adding an entry directly to one of these collections could result in an id conflict. The best solution to this may be to create a dummy user account, but I'll leave it to you to decide.

**Comment by nicholashu** [comment]
I found that out, I set up a flag on the volunteer creation that only deletes and sets the ._id if manualAdd is not true. Otherwise it creates an ObjectID (e.g., 587c2fcade02ac8be4ec8779). And will leave the ID's starting with 10000 to just users. Could either create a different ID set for manual adds e.g., m1000.

**Comment by khawajah** [comment]
Hi..can i take this issue??

**Comment by khawajah** [comment]
can i have more details for this issue please!!
i figured that you need is to let the user admin to add new user without logout ... so add new button called (add new client) with some setting after that should take the user admin to edit page  to fill in the details... is my explain is right? and should i let the user admin when he create new user to choose  (volunteers, clients or donors )

**Comment by nicholashu** [comment]
i've almost finished this. Just need to work out how to make a dummy user account for creation.

**Comment by khawajah** [comment]
you need to create dummy user in database?? can u give me more details please!!
!

**Comment by DealPete** [comment]
Hi Khawajah,

Nicholas has been working on this one for awhile. If you'd like to help out, feel free to check out some of our other issues.

**Comment by nicholashu** [comment]
Im stuck on this one. I can't get the user's ._id from the callback.


```
exports.create = function(req, res) {
	var volunteer = new Volunteer(req.body);
	if (!req.body.manualAdd){
		volunteer._id = req.user._id;
		// Update user's hasApplied property to restrict them from applying again
		User.findOneAndUpdate({_id: volunteer._id}, {$set: {hasApplied: true}})
			.then(function() {
				return volunteer.save(function(err) {
					if (err) {
						return res.status(400).send({
							message: errorHandler.getErrorMessage(err)
						});
					} else {
						return res.json(volunteer);
					}
				});
			})
			.catch(function (err) {
				return res.status(400).send({
					message: errorHandler.getErrorMessage(err)
				});
			});
		}
else{
		var user = new User({
				firstName: 'testing manual add',
				lastName: 'testing manual add',
				provider: 'local',
				username: Date.now(),
				email: 'test@test.com',
				password: 'test1234',
				accountType: ['volunteer']

		});
		user.save(function(data){
			console.log('returned data',res);
			//check for user._id
		});
		volunteer.save(function(err){
			//use user ._id as volunteer id
			if (err) {
				return res.status(400).send({
					message: errorHandler.getErrorMessage(err)
				});
				} else {
					return res.json(volunteer);
				}
		});
	}
	};
```

it's probably something stupid that I have missed.

**Comment by DealPete** [comment]
If I'm not mistaken, the first argument to the callback is the error, and the second is the data. So instead of
		user.save(function(data){
			console.log('returned data',res);
			//check for user._id
		});
you need
		user.save(function(err, data){
			console.log('returned data', data);
			//check for user._id
		});

**Comment by nicholashu** [comment]
Saved the day DealPete
