### ISSUE TITLE
fix vulnerabilities found by snyk.io

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/food-bank-app#17]

**Comment by joshuahenson** [comment]
I can help with this one.

One of the vulnerabilities is related to issue #20. It looks like nunjucks has a pretty similar syntax and it's maintained by Mozilla so it hopefully won't have the same fate as swig. Let me know if that sounds good to you and I'll get to work.

**Comment by DealPete** [comment]
That sounds great, good luck.
