### ISSUE TITLE
Questionnaire editor: Implement dynamic row fields for dependants

### ISSUE THREAD

**Issue by MAF27** [freeCodeCamp/food-bank-app#28]
MAF27 available for background and discussion.

**Comment by kenjiO** [comment]
I finished the first 3 modules of Free Code Camp and Michael Johnson referred me to this project for the last module.  I don't have any experience contributing to open source but I would like to help out.  Can you explain more what you want done with this issue?

**Comment by MAF27** [comment]
Originally, all fields for the customer, volunteer and donor questionnaires were hardcoded to suit the original project's stakeholders. We've made sections A, B and D of the client questionnaire dynamic by implementing a questionnaire editor. You can check this out by cloning the repo, running grunt and logging in with user name admin and password password, then click on Client Database.

Dynamic row fields are needed for Section E, dependants and household. Regular fields won't cut it because you need to be able to dynamically add rows of dependants.

**Comment by kenjiO** [comment]
I think I will try contributing to some other tasks before I take on this one since I am new to angular.  I have been looking through the code and found some small things that might be bugs.  Should I create issues for them or would you prefer I email you first since it might just be some issues with my setup.

**Comment by MAF27** [comment]
Can you email me what you found so far?

**Comment by ProgrammedMikey** [comment]
Did this get added/finished?
When i looked in client database, on E section you can dynamically add up to 20 dependents. What else is needed from this issue

**Comment by MAF27** [comment]
This is still open - what you see now is the static version of the household/dependants section. All other sections have been refactored to use a dynamic form based on fields generated using the Questionnaire Editor (visible if you're logged in as admin).
