### ISSUE TITLE
multiple css warnings when loading page.

### ISSUE THREAD

**Issue by DealPete** [freeCodeCamp/food-bank-app#29]
Find out why this is, and report here.

**Comment by abhishek71994** [comment]
Where is this happening? I am running the app and I cant figure out where. The console is not showing any errors. Please forgive me if I am doing any rookie mistake as this is the first time am trying to contribute.

**Comment by DealPete** [comment]
Hi abhishek, thanks for taking a look at this.
Are you using the Chrome browser? I've been using Safari for development, and when I load the page I get 20 warnings from css files. I just tried Google Chrome and the warnings don't appear, but they do when I use Firefox (when I select "warnings" from the CSS dropdown menu in "Console").

**Comment by abhishek71994** [comment]
I will install and get back to you as soon as possible. Please keep in
touch.

**Comment by abhishek71994** [comment]
Also I will need some guidance regarding where are the CSS and HTML files...

**Comment by DealPete** [comment]
Hi abhishek,

The code is divided into modules, with each module containing it's html and css files in the public/modules/{module name}/{views,css} directory. Having a look at the warnings, though, it seems that they are all from dependencies - AdminLTE for example, is responsible for a lot of them.
There's more information about the structure of the app on the wiki pages.

**Comment by MorganLKestner** [comment]
@DealPete  hey I'm really interested in working on this, is this issue already taken?

**Comment by DealPete** [comment]
Hi Morgan. I haven't heard from abhishek in over a week, so go ahead give it a try. I'm removing the "first-timers-only" tag though - I think this is more difficult than I expected.

**Comment by abhishek71994** [comment]
Sorry I had my semesters going on so had to go off grid because I did not prepare for this semester whatsoever. Fortunately, it went well, I'm back working on this as of now.

**Comment by abhishek71994** [comment]
Okay so I tried fixing the bootstrap errors. Even when I follow the mdn syntax it doesn't work. I did a google search and is it possible, that like other people who have experienced similar errors, mozilla just doesnt work for them?

**Comment by DealPete** [comment]
So it's an issue with mozilla and not with food-bank-app? When you try to load bootstrap from an otherwise blank html file, do you get the same warnings?

**Comment by abhishek71994** [comment]
I'm pretty sure that it's a Mozilla issue. The reason being I made a portfolio website just days ago with good programming practice and still the console shows errors.

**Comment by DealPete** [comment]
That sounds likely. Thanks for your help, abhishek.
