### ISSUE TITLE
Packing lists generated by the application should take into account the number of people in the household.

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/food-bank-app#3]

**Comment by yzhbankov** [comment]
Hello Pete!
How can i generate the packing list in the app or it is not possible in that version?

**Comment by DealPete** [comment]
Right now the packing module figures out how many of each item to send to clients based on the food schedule, and subtracts these items from the inventory when the client is packed. It doesn't take into account how many people are in the client's household, sending the same number of goods to each client.
