### ISSUE TITLE
Inventory menu item not working

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/food-bank-app#45]
When I am logged on as an admin and click on the Inventory menu item I get an error in the web browser console "Could not resolve 'root.foods' from state 'root'".  It looks like the Inventory menu item is created in food.client.config.js and it indicates a route to root.foods but that route is not defined.

**Comment by MAF27** [comment]
Thanks for pointing that out - seems I introduced this bug as part of the Lookup field feature. Fixed.
