### ISSUE TITLE
As a user, I should be able to generate a report of the current food inventory.

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/food-bank-app#7]

**Comment by yzhbankov** [comment]
Hello.
Is this issue about the "Items" table in "Inventory" menu?
Report should be in excel format? Does the user have a possibility to print the page?

**Comment by DealPete** [comment]
I think we're looking for a way to generate a report where the items are broken down by category, along with a summary of how many items are in each category. The report should be printable.
